### ISSUE TITLE
Doesn't show up in modal Dialog

### ISSUE THREAD

**Issue by hujinhui69** [dgoguerra/bootstrap-menu#2]
Doesn't work if you have a table in BootStrap modal. I think it is because the z-index of menu is 1000, but 1050 for .modal. Probably need an option to specify z-index. 

Thanks

**Comment by dgoguerra** [comment]
That's right, fixed by increasing the z-index to 10000.

For now the few styles necessary are added inline to avoid needing to include a BootstrapMenu.css stylesheet to use the package, but you could still make any style changes like this by targetting the `.bootstrapMenu` class, and using `!important` to override any existing inline styles.
